### PR TITLE
Initial migration to null-safety

### PR DESCRIPTION
**Pull request by RyanRamchandar**
I have updated the min Dart version, and migrated the repo to null-safety.

✅ Bumped version to 2.0.0, updated changelog
✅ Regenerated code
✅ Tests and the example are working

@rinukkusu can you merge and publish to pub.dev? Thanks!

### CODE REVIEW

**Comment by RyanRamchandar** [comment]
Fixes #10

**Comment by rinukkusu** [comment]
Thanks for your contribution!! Should be up on Pub soon!

**Comment by RyanRamchandar** [comment]
@rinukkusu https://pub.dev/packages/darksky_weather still shows 1.4.1+1. Were you able to push the new version?

**Comment by rinukkusu** [comment]
Weird, that should've been done by a workflow automatically ... Will check!

**Comment by rinukkusu** [comment]
Seems like the access tokens expired whoops - will fix tonight or tomorrow latest!

**Comment by RyanRamchandar** [comment]
Thank you!

**Comment by rinukkusu** [comment]
@RyanRamchandar it's up! 😄

**Pull request merged**
